require_relative './config/environment'
# using this gem we can run migrate
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end
# Test the class using rake console (or bundle exec rake console)
#rake console # [1] pry(main)> Artist
#=> Artist (call 'Artist.connection' to establish a connection) 
